# Generated by Django 5.2.8 on 2025-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_info', models.JSONField()),
                ('file_thumbnail', models.JSONField(blank=True, null=True)),
                ('file_trailer', models.JSONField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=20)),
                ('status', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('private', 'Private'), ('schedule', 'Schedule'), ('pending', 'Pending'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaHashtag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
