# Generated by Django 5.2.8 on 2026-01-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpuInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('price_per_hour', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
