# Generated by Django 5.2.8 on 2026-01-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpuInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=32)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
    ]
