# Generated by Django 5.2.8 on 2026-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_message_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
