# Generated by Django 5.2.8 on 2026-01-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_message_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='system_message_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
