# Generated by Django 5.2.8 on 2026-02-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_conversation_system_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='external_chat_id',
            field=models.CharField(max_length=20, null=True, blank=True),
        ),
    ]
