# Generated by Django 5.2.8 on 2025-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='provider_payment_id',
            field=models.CharField(max_length=100),
        ),
    ]
